---
refresh_interval: 1 # seconds
max_price: 1600
urls:
  - https://www.amazon.com/dp/B08J5F3G18/
  - https://www.amazon.com/AMD-Radeon-RX-5700-DisplayPort/dp/B08XWRNY2P/
  - https://www.amazon.com/ASUS-3070-Graphics-DisplayPort-Bearings/dp/B08YX5W5PV/
  - https://www.amazon.com/ASUS-Graphics-DisplayPort-Axial-tech-2-7-Slot/dp/B08WGTL4CW/ref=pd_cart_vw_crc_1_1/132-4453211-5946256?_encoding=UTF8&pd_rd_i=B08WGTL4CW&pd_rd_r=31e692d8-49d3-400f-908f-bc4db916b850&pd_rd_w=7OXmz&pd_rd_wg=0Lktt&pf_rd_p=01004c92-8f40-4f1a-bee8-08cb36dccac2&pf_rd_r=TW17PTEAT6ZGXRZGQA53&psc=1&refRID=TW17PTEAT6ZGXRZGQA53
  - https://www.amazon.com/ASUS-Graphics-DisplayPort-Military-Grade-Certification/dp/B08HH5WF97
  - https://www.amazon.com/EVGA-GeForce-Technology-Backplate-24G-P5-3987-KR/dp/B08J5F3G18/
  - https://www.amazon.com/Gaming-GeForce-Graphics-DisplayPort-Bearings/dp/B08Y9B8L43/
  - https://www.amazon.com/gp/product/B08HR3Y5GQ/ # EVGA 10G-P5-3897-KR GeForce RTX 3080
  - https://www.amazon.com/MSI-Gaming-RTX-2060-Super/dp/B07V1Q4L2Z
  - https://www.amazon.com/MSI-GeForce-320-Bit-Architecture-Graphics/dp/B08HR5SXPS
  - https://www.amazon.com/MSI-GeForce-Architecture-Overclocked-Graphics/dp/B07V265ZBH
  - https://www.amazon.com/MSI-GeForce-Architecture-Overclocked-Graphics/dp/B07V39YSPF
  - https://www.amazon.com/MSI-GeForce-RTX-3080-10G/dp/B08HR7SV3M
  - https://www.amazon.com/MSI-GeForce-RTX-3090-VENTUS/dp/B08HR9D2JS
  - https://www.amazon.com/MSI-GeForce-Tri-Frozr-Architecture-Graphics/dp/B08HR7SV3M
  - https://www.amazon.com/MSI-GeForce-Tri-Frozr-Architecture-Graphics/dp/B08HRBW6VB
  - https://www.amazon.com/MSI-Radeon-6800-Architecture-16G/dp/B08RJ6YBH5/
  - https://www.amazon.com/sm/dp/B08WHJPBFX
  - https://www.amd.com/en/direct-buy/5458372200/us # AMD Radeon RX 6900 XT Graphics
  - https://www.amd.com/en/direct-buy/5458372800/us # AMD Radeon RX 6800 XT Graphics
  - https://www.amd.com/en/direct-buy/5458373400/us # AMD Radeon RX 6800 Graphics
  - https://www.amd.com/en/direct-buy/5496921400/us # AMD Radeon™ RX 6700 XT Graphics
  - https://www.bestbuy.com/site/gigabyte-amd-radeon-rx-6800-aorus-master-16gb-gddr6-pci-express-4-0-graphics-card/6453894.p?skuId=6453894
  - https://www.bestbuy.com/site/gigabyte-amd-radeon-rx-6800-gaming-oc-16gb-gddr6-pci-express-4-0-graphics-card/6453897.p?skuId=6453897
  - https://www.bestbuy.com/site/gigabyte-amd-radeon-rx-6800-xt-aorus-master-16gb-gddr6-pci-express-4-0-graphics-card/6453895.p?skuId=6453895
  - https://www.bestbuy.com/site/gigabyte-amd-radeon-rx-6800-xt-gaming-oc-16gb-gddr6-pci-express-4-0-graphics-card/6453896.p?skuId=6453896
  - https://www.bestbuy.com/site/msi-amd-radeon-rx-6800-16g-16gb-gddr6-pci-express-4-0-graphics-card-black-black/6441020.p?skuId=6441020
  - https://www.bestbuy.com/site/msi-amd-radeon-rx-6800-gaming-x-trio-16g-16gb-gddr6-pci-express-4-0-graphics-card/6447182.p?skuId=6447182
  - https://www.bestbuy.com/site/msi-amd-radeon-rx-6800-xt-16g-16gb-gddr6-pci-express-4-0-graphics-card-black/6440913.p?skuId=6440913
  - https://www.bestbuy.com/site/msi-amd-radeon-rx-6900-xt-16g-gddr6-pci-express-4-0-graphics-card-black-silver/6444716.p?skuId=6444716
  - https://www.bestbuy.com/site/msi-radeon-rx-6800-xt-16g-16gb-gddr6-pci-express-4-0-graphics-card-black-black/6440913.p?skuId=6440913
  - https://www.bestbuy.com/site/nintendo-joy-con-l-r-the-legend-of-zelda-skyward-sword-hd-edition/6454021.p?skuId=6454021 # Zelda Joycons
  - https://www.microcenter.com/product/628303/asus-geforce-rtx-3080-tuf-gaming-triple-fan-10gb-gddr6x-pcie-40-graphics-card?storeid=075
  - https://www.microcenter.com/product/628318/asus-geforce-rtx-3080-tuf-gaming-overclocked-triple-fan-10gb-gddr6x-pcie-40-graphics-card?storeid=075
  - https://www.microcenter.com/product/628330/msi-geforce-rtx-3080-gaming-x-trio-triple-fan-10gb-gddr6x-pcie-40-graphics-card?storeid=075
  - https://www.microcenter.com/product/628331/msi-geforce-rtx-3080-ventus-3x-overclocked-triple-fan-10gb-gddr6x-pcie-40-graphics-card?storeid=075
  - https://www.microcenter.com/product/628344/evga-geforce-rtx-3080-xc3-ultra-gaming-triple-fan-10gb-gddr6x-pcie-40-graphics-card?storeid=075
  - https://www.microcenter.com/product/628346/evga-geforce-rtx-3080-ftw3-ultra-gaming-triple-fan-10gb-gddr6x-pcie-40-graphics-card?storeid=075
  - https://www.microcenter.com/product/628686/asus-geforce-rtx-3080-strix-overclocked-triple-fan-10gb-gddr6x-pcie-40-graphics-card?storeid=075
  - https://www.microcenter.com/product/630033/gigabyte-geforce-rtx-3070-gaming-overclocked-triple-fan-8gb-gddr6-pcie-40-graphics-card?storeid=075
  - https://www.microcenter.com/product/630201/msi-geforce-rtx-3070-gaming-x-trio-triple-fan-8gb-gddr6-pcie-40-graphics-card?storeid=075
  - https://www.microcenter.com/product/630202/msi-geforce-rtx-3070-ventus-3x-overclocked-triple-fan-8gb-gddr6-pcie-40-graphics-card?storeid=075
  - https://www.microcenter.com/product/630579/evga-geforce-rtx-3070-xc3-black-gaming-triple-fan-8gb-gddr6-pcie-40-graphics-card?storeid=075
  - https://www.microcenter.com/product/630686/asus-geforce-rtx-3070-rog-strix-overclocked-dual-fan-8gb-gddr6-pcie-40-graphics-card?storeid=075
  - https://www.microcenter.com/product/631533/msi-geforce-rtx-3080-suprim-x-overclocked-triple-fan-10gb-gddr6x-pcie-40-graphics-card?storeid=075
  - https://www.microcenter.com/product/631692/asus-radeon-rx-6800-xt-rog-strix-lc-overclocked-hybrid-cooled-16gb-gddr6-pcie-40-graphics-card?storeid=075
  - https://www.microcenter.com/product/631693/asus-radeon-rx-6800-xt-tuf-gaming-overclocked-triple-fan-16gb-gddr6-pcie-40-graphics-card?storeid=075
  - https://www.microcenter.com/product/631770/asrock-amd-radeon-rx-6800-xt-phantom-gaming-overclocked-triple-fan-16gb-gddr6-pcie-40-graphics-card?storeid=075
  - https://www.microcenter.com/product/631918/sapphire-technology-amd-radeon-rx-6800-xt-nitro-se-overclocked-triple-fan-16gb-gddr6-pcie-40-graphics-card?storeid=075
  - https://www.microcenter.com/product/631919/sapphire-technology-amd-radeon-rx-6800-xt-nitro-gaming-overclocked-triple-fan-16gb-gddr6-pcie-40-graphics-card?storeid=075
  - https://www.microcenter.com/product/632050/asus-amd-radeon-rx-6900-xt-triple-fan-16gb-gddr6-pcie-40-graphics-card?storeid=075
  - https://www.microcenter.com/product/632292/asus-amd-radeon-rx-6900-xt-tuf-gaming-overclocked-triple-fan-16gb-gddr6-pcie-40-graphics-card?storeid=075
  - https://www.microcenter.com/product/632471/sapphire-technology-amd-radeon-rx-6900-xt-nitro-overclocked-triple-fan-16gb-gddr6-pcie-40-graphics-card?storeid=075
  - https://www.microcenter.com/product/632555/msi-amd-radeon-rx-6800-xt-gaming-x-trio-overclocked-triple-fan-16gb-gddr6-pcie-40-graphics-card?storeid=075
  - https://www.microcenter.com/product/632683/asus-amd-radeon-rx-6900-xt-rog-strix-overclocked-hybrid-cooled-16gb-gddr6-pcie-40-graphics-card?storeid=075
  - https://www.microcenter.com/product/634191/msi-amd-radeon-rx-6900-xt-gaming-x-trio-triple-fan-16gb-gddr6-pcie-40-graphics-card?storeid=075
  - https://www.microcenter.com/product/634956/sapphire-technology-amd-radeon-rx-6900-xt-sapphire-toxic-overclocked-hybrid-cooled-16gb-gddr6-pcie-40-graphics-card?storeid=075
  - https://www.newegg.com/asrock-radeon-rx-6700-xt-rx6700xt-cld-12g/p/N82E16814930056
  - https://www.newegg.com/asrock-radeon-rx-6700-xt-rx6700xt-clp-12go/p/N82E16814930055
  - https://www.newegg.com/asrock-radeon-rx-6700-xt-rx6700xt-pgd-12go/p/N82E16814930054
  - https://www.newegg.com/asrock-radeon-rx-6800-rx-6800-16g/p/N82E16814930046
  - https://www.newegg.com/asrock-radeon-rx-6800-xt-rx-6800-xt-16g/p/N82E16814930045
  - https://www.newegg.com/asus-geforce-rtx-3080-rog-strix-rtx3080-o10g-gaming/p/N82E16814126457
  - https://www.newegg.com/asus-geforce-rtx-3080-tuf-rtx3080-10g-gaming/p/N82E16814126453
  - https://www.newegg.com/asus-geforce-rtx-3080-tuf-rtx3080-o10g-gaming/p/N82E16814126452
  - https://www.newegg.com/asus-radeon-rx-6700-xt-dual-rx6700xt-12g/p/N82E16814126500
  - https://www.newegg.com/asus-radeon-rx-6700-xt-rog-strix-rx6700xt-o12g-gaming/p/N82E16814126498
  - https://www.newegg.com/asus-radeon-rx-6700-xt-rx6700xt-12g/p/N82E16814126502
  - https://www.newegg.com/asus-radeon-rx-6700-xt-tuf-rx6700xt-o12g-gaming/p/N82E16814126499
  - https://www.newegg.com/asus-radeon-rx-6800-rx6800-16g/p/N82E16814126473
  - https://www.newegg.com/asus-radeon-rx-6800-xt-rx6800xt-16g/p/N82E16814126472
  - https://www.newegg.com/asus-radeon-rx-6800-xt-tuf-rx6800xt-o16g-gaming/p/N82E16814126476
  - https://www.newegg.com/asus-radeon-rx-6800-xt-tuf-rx6800xt-o16g-gaming/p/N82E16814126476 # ASUS TUF Gaming Radeon RX 6800 XT
  - https://www.newegg.com/evga-geforce-rtx-3080-10g-p5-3881-kr/p/N82E16814487522
  - https://www.newegg.com/evga-geforce-rtx-3080-10g-p5-3883-kr/p/N82E16814487521
  - https://www.newegg.com/evga-geforce-rtx-3080-10g-p5-3885-kr/p/N82E16814487520
  - https://www.newegg.com/evga-geforce-rtx-3080-10g-p5-3895-kr/p/N82E16814487519
  - https://www.newegg.com/evga-geforce-rtx-3080-10g-p5-3897-kr/p/N82E16814487518
  - https://www.newegg.com/gigabyte-geforce-rtx-3080-gv-n3080aorus-m-10gd/p/N82E16814932336
  - https://www.newegg.com/gigabyte-geforce-rtx-3080-gv-n3080aorus-x-10gd/p/N82E16814932345
  - https://www.newegg.com/gigabyte-geforce-rtx-3080-gv-n3080eagle-10gd/p/N82E16814932367
  - https://www.newegg.com/gigabyte-geforce-rtx-3080-gv-n3080eagle-oc-10gd/p/N82E16814932330
  - https://www.newegg.com/gigabyte-geforce-rtx-3080-gv-n3080gaming-oc-10gd/p/N82E16814932329
  - https://www.newegg.com/gigabyte-geforce-rtx-3080-gv-n3080vision-oc-10gd/p/N82E16814932337
  - https://www.newegg.com/gigabyte-radeon-rx-6700-xt-gv-r67xt-12gd-b/p/N82E16814932417
  - https://www.newegg.com/gigabyte-radeon-rx-6700-xt-gv-r67xtaorus-e-12gd/p/N82E16814932415
  - https://www.newegg.com/gigabyte-radeon-rx-6700-xt-gv-r67xteagle-12gd/p/N82E16814932418
  - https://www.newegg.com/gigabyte-radeon-rx-6700-xt-gv-r67xtgaming-oc-12gd/p/N82E16814932416
  - https://www.newegg.com/gigabyte-radeon-rx-6800-gv-r68-16gc-b/p/N82E16814932374
  - https://www.newegg.com/gigabyte-radeon-rx-6800-gv-r68aorus-m-16gd/p/N82E16814932393
  - https://www.newegg.com/gigabyte-radeon-rx-6800-gv-r68gaming-oc-16gd/p/N82E16814932382
  - https://www.newegg.com/gigabyte-radeon-rx-6800-xt-gv-r68xt-16gc-b/p/N82E16814932373
  - https://www.newegg.com/gigabyte-radeon-rx-6800-xt-gv-r68xtaorus-m-16gc/p/N82E16814932392
  - https://www.newegg.com/gigabyte-radeon-rx-6800-xt-gv-r68xtaorus-m-16gd/p/N82E16814932395
  - https://www.newegg.com/gigabyte-radeon-rx-6800-xt-gv-r68xtgaming-oc-16gd/p/N82E16814932381
  - https://www.newegg.com/gigabyte-radeon-rx-6900-xt-gv-r69xtaorus-m-16gd/p/N82E16814932413
  - https://www.newegg.com/msi-geforce-rtx-3060-rtx-3060-gaming-x-12g/p/N82E16814137630
  - https://www.newegg.com/msi-geforce-rtx-3060-rtx-3060-gaming-x-trio-12g/p/N82E16814137629
  - https://www.newegg.com/msi-geforce-rtx-3060-rtx-3060-ventus-2x-12g-oc/p/N82E16814137632
  - https://www.newegg.com/msi-geforce-rtx-3060-rtx-3060-ventus-2x-12g/p/N82E16814137638
  - https://www.newegg.com/msi-geforce-rtx-3060-rtx-3060-ventus-3x-12g-oc/p/N82E16814137631
  - https://www.newegg.com/msi-geforce-rtx-3080-rtx-3080-gaming-x-trio-10g/p/N82E16814137597
  - https://www.newegg.com/msi-geforce-rtx-3080-rtx-3080-ventus-3x-10g-oc/p/N82E16814137598
  - https://www.newegg.com/msi-geforce-rtx-3080-rtx-3080-ventus-3x-10g/p/N82E16814137600
  - https://www.newegg.com/msi-geforce-rtx-3080-rtx3080-suprim-x-10g/p/N82E16814137609
  - https://www.newegg.com/msi-radeon-rx-6700-xt-rx-6700-xt-gaming-x-12g/p/N82E16814137642
  - https://www.newegg.com/msi-radeon-rx-6700-xt-rx-6700-xt-mech-2x-12g/p/N82E16814137641
  - https://www.newegg.com/msi-radeon-rx-6800-rx-6800-16g/p/N82E16814137608
  - https://www.newegg.com/msi-radeon-rx-6800-rx-6800-gaming-x-trio-16g/p/N82E16814137622
  - https://www.newegg.com/msi-radeon-rx-6800-xt-rx-6800-xt-16g/p/N82E16814137607
  - https://www.newegg.com/msi-radeon-rx-6800-xt-rx-6800-xt-gaming-x-trio-16g/p/N82E16814137621
  - https://www.newegg.com/msi-radeon-rx-6900-xt-rx-6900-xt-gaming-x-trio-16g/p/N82E16814137628
  - https://www.newegg.com/msi-rx6700xtmech-2x12goc/p/N82E16814137640
  - https://www.newegg.com/sapphire-radeon-rx-6700-xt-11306-01-20g/p/N82E16814202399
  - https://www.newegg.com/sapphire-radeon-rx-6700-xt-11306-02-20g/p/N82E16814202400
  - https://www.newegg.com/sapphire-radeon-rx-6700-xt-21306-01-20g/p/N82E16814202398
  - https://www.newegg.com/sapphire-radeon-rx-6800-21305-01-20g/p/N82E16814202389
  - https://www.newegg.com/sapphire-radeon-rx-6800-xt-21304-01-20g/p/N82E16814202388
  - https://www.newegg.com/sapphire-radeon-rx-6900-xt-11308-04-20g/p/N82E16814202397
...